- name: "Put composer to /usr/local/bin"
  copy: src=composer dest=/usr/local/bin owner=root group=root mode=0755
- name: "Update composer"
  command: /usr/local/bin/composer self-update

- name: "Add path for composer to root user's .bashrc"
  lineinfile: >-
    dest='/root/.bashrc'
    state=present
    line="export PATH=$HOME/.composer/vendor/bin:$PATH"

#- name: "Install composer"
#  shell: >
#    php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php &&
#    php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) === '7228c001f88bee97506740ef0888240bd8a760b046ee16db8f4095c0d8d525f2367663f22a46b48d072c816e7fe19959') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" &&
#    php composer-setup.php --filename=composer &&
#    php -r "unlink('composer-setup.php');"
#  args:
#    chdir: /usr/local/bin
#    creates: /usr/local/bin/composer

