# Create database & user
- name: "Create user"
  mysql_user:
    name: "{{item.user}}"
    password: "{{item.password}}"
    priv: "*.*:ALL"
    state: present
  with_items: "{{databases}}"
- name: "Create database"
  mysql_db:
    name: "{{item.name}}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  with_items: "{{databases}}"

